//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleChatbotApi.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChatbotServiceResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChatbotServiceResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleChatbotApi.Resource.ChatbotServiceResponses", typeof(ChatbotServiceResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sed rhoncus dapibus sem, a laoreet felis posuere et. Vestibulum tincidunt pulvinar nibh. Suspendisse condimentum rutrum vestibulum. In interdum porta neque, vitae sodales tellus vulputate nec. Proin pulvinar rutrum vehicula. Proin vel nisl ante. Aliquam luctus commodo tortor, sit amet vestibulum purus. Donec in bibendum dui, et consectetur libero. Aliquam lacus enim, sagittis at risus sit amet, ultricies eleifend dui. Duis blandit turpis eu ex aliquet auctor in sed leo. Morbi feugiat est ac enim tristique c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Long {
            get {
                return ResourceManager.GetString("Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donec non nisl in nisl imperdiet lobortis. Proin id felis ante. Maecenas tempor elit augue, ut ultricies lorem ullamcorper nec. Donec aliquam orci sit amet venenatis gravida. Vestibulum vitae faucibus orci. Donec gravida mi sed sem tristique faucibus. Sed placerat tincidunt suscipit. Donec egestas metus gravida, feugiat felis id, blandit magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi convallis placerat lorem id feugiat. Integer libero orci, pretium ac imperdiet ac, tempor sit amet dui [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ut nibh rhoncus, consectetur ex et, ultricies dui. Ut lobortis nec purus eu aliquet..
        /// </summary>
        internal static string Short {
            get {
                return ResourceManager.GetString("Short", resourceCulture);
            }
        }
    }
}
